name: Comment on PR

on:
  workflow_run:
    workflows:
      - "Test"
      - "Absinthe Federation Test"
      - "Apollo Server Test"
      - "Ariadne Test"
      - "AWS AppSync Test"
      - "Caliban Test"
      - "Dgraph Test"
      - "DGS Test"
      - "Express GraphQL Test"
      - "Federation JVM Test"
      - "GQLGen Test"
      - "Graphene Test"
      - "GraphQL for .Net Test"
      - "GraphQL Go Test"
      - "GraphQL Helix Test"
      - "GraphQL Java Kickstart Test"
      - "GraphQL Kotlin Test"
      - "GraphQL Mesh Test"
      - "GraphQL Yoga Test"
      - "HotChocolate Test"
      - "Lighthouse Test"
      - "Mercurius Test"
      - "NestJS (Code First) Test"
      - "NestJS (SDL First) Test"
      - "Apollo Federation PHP Test"
      - "Pothos Test"
      - "GraphQL Ruby Test"
      - "Sangria Test"
      - "StepZen Test"
      - "Strawberry GraphQL Test"
    types:
      - completed

jobs:
  comment:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
      - name: Standardize artifact names
        run: mv results*/results*.md results.md
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            var issue_number = Number(fs.readFileSync('.pr/pr_info'));
            const results = fs.readFileSync('results.md', 'utf-8');
            const commentBody = `## Apollo Federation Subgraph Compatibility Results\n${results}\n`;
            github.rest.issues.createComment({
              issue_number: issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
