name: Subgraph Test

on:
  workflow_call:
    inputs:
      library:
        required: true
        type: string

jobs:
  compatibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm install
      - run: npm run setup
      - run: npm run test ${{ inputs.library }}
        env:
          DEBUG: docker,test
      - run: cat results.md
      - name: results summary
        run: cat results.md >> $GITHUB_STEP_SUMMARY
