name: Apollo Server Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'implementations/apollo-server/**'

jobs:
  compatibility:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/test-subgraph.yml
        with:
          library: "apollo-server"
