name: Absinthe Federation Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'implementations/absinthe-federation/**'

jobs:
  compatibility:
    runs-on: ubuntu-latest
    - uses: ./.github/workflows/test-subgraph.yml
      with:
        library: "absinthe-federation"
